# Generated by Django 4.1.7 on 2023-04-03 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facebookgroup',
            name='group',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
